# Dockerfile para clientes con Firefox
FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y firefox x11-apps net-tools iproute2 iputils-ping && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Instalar utilidades para terminal
RUN apt-get install -y nano curl

CMD ["bash"]
